### ISSUE TITLE
Command [x] is currently not enabled and can not be run.

### ISSUE THREAD

**Issue by gnowland** [fabiospampinato/vscode-statusbar-debugger#3] opened 2017-08-15 18:18 UTC
For example:
`Warn: Command 'Continue' is currently not enabled and can not be run.`

I think it would be really helpful if the currently disabled commands were grayed out... is this possible?

**Comment by fabiospampinato** [comment] 2017-08-16 11:05
Unfortunately at the moment there's no way of knowing if a debug session is paused or not.

Having that information we could gray-out those icons and merge pause/play into a single button.

We'll have to wait for [this](https://github.com/Microsoft/vscode/issues/30810) upstream issue.

**Comment by gnowland** [comment] 2017-08-16 17:26
Ah, I figured there was probably an API functionality limitation regarding this. Thanks for the reply!

**Comment by fabiospampinato** [comment] 2021-04-02 15:28
Duplicate of #15

**Closed by fabiospampinato** 2021-04-02 15:28 UTC
Labels: enhancement, missing api
